spring:
  application:
    name: customer-service-app
server:
  port: 9502
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9500/eureka
    register-with-eureka: true
    fetch-registry: true

