spring:
  application:
    name: eureka-server
  zipkin:
    enabled: true
    base-url: http://localhost:9506
server:
  port: 9500
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
