

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9500/eureka

spring:
  application:
    name: config-server
  profiles:
    active: git,native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BarathArivazhagan/ConfigServerRepo.git
          order: 1
          search-paths: '{application}'
        native:
          order: 2
          search-locations:

          - classpath:/config/{application}/

  zipkin:
    base-url: http://localhost:9506
server:
  port: 8888